apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-node-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/satyakatta1988-afk/KubeTraining.git
    targetRevision: HEAD
    path: charts/simple-node-app
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
