replicaCount: 1

image:
  repository: satyakatta1988/simple-node-app
  tag: v1
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

